#+title: Систем Крафтинг. Часть 1
#+author: Dmitry Klementiev
#+email: klementievdmitry@gmail.com

В этом эпизоде я собираюсь рассказать о выборе пакетного менеджера, дистрибутива, редактора кода, оконного менеджера, и.т.д.

Хотелось бы обратить внимание на то, что эта и все последующие части данного блога будут исключительно на русском языке (хотя мне бы очень хотелось их перевести). Причиной тому стало то, что я очень недолго учу английский и писать блог для меня немного сложновато.

* Дистрибутив и пакетный менеджер

Изначально я выбирал из следующих вариантов:
- Gentoo
- Arch
- NixOS
- GuixSD

** Gentoo

Генту был идеальным вариантом, пока я не узнал о никс и гикс, но о них немного позже.

Как по мне, у данного дистрибутива есть лишь один существенный минус, сборка из исходного кода. Сборка каждого пакета из исходников занимает очень много времени на моей машине, в особенности если это браузер по типу Firefox. Но у генту также есть множество бинарных пакетов.

В остальном я выделял только плюсы. Сборка из исходного кода позволяла оптимизировать пакеты под мою машину. На gentoo проще всего определять свои пакеты которых нет в репозиториях (таковых очень мало).

По мимо этого я также выделил следующие плюсы:
- OpenRC вместо SystemD - Я стараюсь избегать системд там, где это возможно. Если такой возможности нет, то я не стану капризничать =)
- Конструктор - Мне нравится то как происходит установка Gentoo. Я обожаю устанавливать что-то своими руками и когда система ведёт себя так, как это хочу я.
- Gentoo book - Увы, единственный конкурент Arch Wiki который мне известен.
- Большое кол-во пакетов
- Большая приспособленность к системному админимтрированию - т.е сюда входит определение собственных пакетов (бинарных в том числе)

*Почему же я ушёл от генту?* Всё потому что я вовремя открыл для себя Nix и Guix.

** Arch

Отличный дистрибутив, но след. вещи меня в нем не устроили:
- Нестабильность - Вот все хорошо работает, а вот ты запустил =pacman -Syu= и не работает нихуя. /НО хочется заметить что я бы мог просто делать резервные копии, и вы можете также (:/
- Сложность определения собственных пакетов
- SystemD - Artix в свою очередь мне чем-то не угодил. А вот чем я уже не помню

** NixOS & GuixSD

Я считаю их почти идентичными, поэтому их выбор лишь дело вкуса.

|                        | *Nix*     | *Guix*                        |
| *System initialization*  | /SystemD/ | /GNU Shepherd/                |
| *Scripting langauge*     | /Nix DSL/ | /Guile (Scheme)/              |
| *Proprietary packages*   | /Yes/     | /No (only third-party repos)/ |
